version: "3"

tasks:

  start:
    desc: Starts application locally with reload enabled
    cmds:
    - uvicorn main:app --reload

  build:
    desc: Build Docker image and tag it as "spedfastapi"
    cmds:
    - docker build -t spedfastapi .

  run:
    desc: Create container using "spedfastapi" image and use .env file
    cmds:
    - docker run -d --rm --name fastapi -p 8000:8000 --env-file .env spedfastapi

  stop:
    desc: Kill container called "spedfastapi"
    cmds:
    - docker kill fastapi

  clean:
    desc: Clean up Docker on system
    cmds:
    - docker system prune -f

  upload:
    desc: Re-tag docker image and upload to Tustin USD Azure container registry
    cmds:
    - docker tag spedfastapi <TUSD container registry>.azurecr.io/spedfastapi
    - docker push <TUSD container registry>.azurecr.io/spedfastapi