version: "3"

tasks:

  start:
    desc: Starts application locally with reload
    cmds:
    - uvicorn main:app --reload

  build:
    desc: Build Docker image and tag it as "spedfastapi"
    cmds:
    - docker build -t spedfastapi .

  run:
    desc: Create container using "spedfastapi" image and use .env file
    cmds:
    - docker run -d --rm --name fastapi -p 8000:8000 --env-file .env spedfastapi

  stop_container:
    desc: Kill container called "spedfastapi"
    cmds:
    - docker kill fastapi

  clean_docker:
    desc: Clean up Docker on system
    cmds:
    - docker system prune -f